### PR TITLE
Add IPA_Font_License_Agreement_v1.0.txt

### PR DESCRIPTION
**Pull request by shiwano**
IPA Font License Agreement file is required to re-distribute [the IPA font](https://github.com/KLab/PlaygroundOSS/blob/master/Engine/fonts/ipagp.ttf).

See also [IPAフォントの再配布について](http://ipafont.ipa.go.jp/faq.html#q002).

### CODE REVIEW

**Comment by shiwano** [comment]
I noticed #7 issue just now.

**Comment by muojp** [comment]
thanks for your contribute.

ref: #7

**Comment by muojp** [comment]
We still need to consider where to put license files of third party libraries in
- PlaygroundOSS root directory
- each libraries' root directory
- aggregated "third party licenses" directory (e.g. /ThirdPartyLicenses)

**Comment by shiwano** [comment]
Thanks!

**Pull request merged**
