### PR TITLE
Convert format from docx to pdf.

### PR DESCRIPTION
**Pull request by futoase**
I think `pdf` is pragmatic reading format.

### CODE REVIEW

**Comment by muojp** [comment]
wow, much better. thanks

**Comment by muojp** [comment]
Reviewed and found current version of Toboggan_Operation_Manual_JP.docx has some errors but it's another issue. Anyway, merged. By the way, what did you use to export PDF from docx? MS Word, LibreOffice, or other? We'd like to know it for further maintenance of these files. thanks.

**Comment by futoase** [comment]
> By the way, what did you use to export PDF from docx? MS Word, LibreOffice, or other?

I use Mac OS X PDF export function after upload to Google Drive.

**Comment by muojp** [comment]
:+1: easy to reproduce. great

**Pull request merged**
