### PR TITLE
Modified: Remove u's comment line.

### PR DESCRIPTION
**Pull request by futoase**
Remove `μ's` comment line.

### CODE REVIEW

**Comment by muojp** [comment]
It's harmless but splitting "project specific" stuff out of generic project is good thing, yes. thanks.

**Comment by futoase** [comment]
I understand!

**Comment by muojp** [comment]
sorry, wasn't meant to reject this PR. just wanted to have some moment to keep notes of these comments in our internal wiki to safely remove them.

**Comment by futoase** [comment]
:+1:

**Comment by futoase** [comment]
:smiley_cat:

**Comment by muojp** [comment]
:v:

**Pull request merged**
